{% set name = "cloud-sql-python-connector" %}
{% set version = "1.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cloud-sql-python-connector-{{ version }}.tar.gz
  sha256: e708b935dc0b52e330cd6c71cd8f17e171a30090fe93e6dbfc1b4a87da10e1e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp
    - cryptography
    - google-api-python-client
    - pyopenssl
    - python >=3.6
    - requests

test:
  imports:
    - google
    - google.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector
  summary: The Cloud SQL Python Connector is a library that can be used alongside a database driver to allow users with sufficient permissions to connect to a Cloud SQL database without having to manually allowlist IPs or manage SSL certificates.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
