schema_version: 1

context:
  name: cloud-sql-python-connector
  version: 1.11.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cloud-sql-python-connector-${{ version }}.tar.gz
  sha256: c8235589e30a6702e3bdb2408d30be06160b18e573812b88dec5ac6606efb6d5

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - aiohttp
    - cryptography
    - google-api-python-client
    - pyopenssl
    - python >=${{ python_min }}
    - requests

tests:
  - python:
      imports:
        - google
        - google.cloud
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: The Cloud SQL Python Connector is a library that can be used alongside a database driver to allow users with sufficient permissions to connect to a Cloud SQL database without having to manually allowlist IPs or manage SSL certificates.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector

extra:
  recipe-maintainers:
    - janjagusch
